#!/usr/bin/python3

"""
This module is responsible for running the cli installer.
"""

from core import logger, start
from platform import system, release, python_version


def main():
    logger.info(
        f'Starting in "{system()} {release()}" with "python {python_version()}"'
    )
    start()


if __name__ == "__main__":
    main()
