#!/usr/bin/python3

"""
This module is responsible for running the cli installer.
"""

from core import logger, start
from core.color import error
from core.utilities import get_os_name
from core.constants import ARCH, DEBIAN, FEDORA, MANJARO
from platform import system, release, python_version


def main():
    logger.info(
        f'Starting in "{system()} {release()}" with "python {python_version()}"'
    )
    os_name = get_os_name()
    if os_name in [ARCH, DEBIAN, FEDORA, MANJARO]:
        logger.logger.info(
            f'The underlying operating system was found to belong to the "{os_name}" family'
        )
        start()
    else:
        logger.logger.error("This system is not currently supported")
        error("This script is not supported for your system")


if __name__ == "__main__":
    main()
